### PR TITLE
Live MAC Layer Trace in UDP Framing 

### PR DESCRIPTION
**Pull request by davidrupprecht**
Hi,

I have added a live MAC layer trace functionality, that allows to retrieve a live trace on the mac layer. The mac frame is encapsulated into a UDP datagram and can be decoded with wireshark and the heuristic decoder. 

Best regards,
David

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Hey David, sorry for the late response regarding this PR. I've looked through it again (I, of course, did initially) and noticed that you've implemented this for the eNB only. Do you see any reason why this wouldn't work with the UE?

**Comment by davidrupprecht** [comment]
Hi Andre,

No, I do not see any reason why this wouldn’t work with UE. I just needed it for the enodeb and I thought it might be useful to share the code. 

Best,
David

**Comment by andrepuschmann** [comment]
Hey David, just picking this up again. Would be great to have this merged into next before the autumn release. Do you have the resources to rebase the code on next? Also I'd have a few comments on the naming and configuration of it. How would you like to proceed with that?

**Comment by davidrupprecht** [comment]
closed for new pull request.

**Pull request closed without merging**
