### PR TITLE
Include current time in EMM information

### PR DESCRIPTION
**Pull request by dillona**

### CODE REVIEW

**Comment by andrepuschmann** [comment]
That looks good to me. Thanks for this, and also for addressing the LGTM warning. Have you tried this with a COTS phone or srsUE and have a Wireshark capture to share?

**Comment by dillona** [comment]
Sure: [epc.pcap.zip](https://github.com/srsLTE/srsLTE/files/5348264/epc.pcap.zip)

**Comment by dillona** [comment]
Is there any more info you need from me for this?

**Comment by andrepuschmann** [comment]
Dillon, thanks for the contribution. Nothing else needed, I checked and it works well. I'll close the PR because I've cherry-picked your commit on our current next branch and resolved some conflicts manually. It will be included in the 20.10 release. Thanks for the contribution

**Pull request closed without merging**
