### PR TITLE
added shared memory messaging faux rf device (rebase #148)

### PR DESCRIPTION
**Pull request by jgiovatto**
allows enb/ue communication at the rf device level.

### CODE REVIEW

**Comment by pgorczak** [comment]
This is a great idea! I could run enb and ue with the device but it seems like attach is not working. The UE finds the cell but then ends up repeating warnings (normally the message *Found PLMN...* should come next in the UE log):

#### eNB

    [DMY] [I] rf_dummy_recv_with_time_multi nsamples 5760 1538467818:0.083904
    [DMY] [I] rf_dummy_send_timed_multi nsamples 5760, sob 0, eob 0
    # Goes on forever

#### UE

    [DMY] [I] rf_dummy_recv_with_time_multi nsamples 9600 1538467636:0.587993
    # Above repeats a few times followed by
    [NAS ] [W] Did not find any PLMN in the set of frequencies
    # Goes on forever

**Comment by jgiovatto** [comment]
Looking at the logs "DMY" is dummy rf which has no backend.
The enb/ue.conf device_name should be "shmemrf" and the args set to "enb" or "ue.
I added sample config here:
```
srsenb/enb.conf.fauxrf.example
srsue/ue.conf.fauxrf.example
```
please note that these also include the mbms.

**Comment by pgorczak** [comment]
Could reproduce a working connection with *shmemrf*. Thanks for the clarification!

**Comment by jgiovatto** [comment]
Great thanks for trying. You might be able to run multiple ue's. The problem here is network namespace isolation for the ue tun interfaces. It would be ideal to run each application (ue/enb/epc) in its own "lxc container", but shared memory segments are no longer global then, will need a way to set the shared memory segments as a common resource for all processes.

**Comment by pgorczak** [comment]
Docker [can control IPC scopes](https://docs.docker.com/engine/reference/run/#ipc-settings---ipc) and I'm already working with it. I'm a little busy right now but will try running multiple UEs using that approach.

**Comment by GinesGarcia** [comment]
Hi!
sounds really interesting!!
I'll take a look to the implementation in order to try to help somehow.

**Comment by jgiovatto** [comment]
Hi I added some comments at the top of lib/src/phy/rf/rf_shmem_imp.c.
You can contact me w/any detailed question.

**Comment by GinesGarcia** [comment]
Thanks a lot for the information!!
Could I have your contact information? because I have some questions :)

Regards,
Ginés.

**Comment by jgiovatto** [comment]
> Thanks a lot for the information!!
> Could I have your contact information? because I have some questions :)
> 
> Regards,
> Ginés.

I updated my profile its: jgiovatto@adjacentlink.com
sorry for the chatter.

**Comment by saminiir** [comment]
Got this working too running on Arch Linux with October package mirror.

How do I send IP traffic through the UE though? I got the `tun_srsue` interface with 172.16.0.3/24 and `srs_spgw_sgi` interface with 172.16.0.1/24 up, and `srsepc` and `srsenb` are logging seemingly good connection with the UE.

**Comment by jgiovatto** [comment]
You will need to run the epc/ue in a different network namespace otherwise your ping is interpreted as localhost destination. You can try running the epc in a different machine or linux container. The ue currently needs to run on the same platform as the enb since it uses a SV-IPC shared memory backend.

**Comment by FabianEckermann** [comment]
I replaced the System V IPC with [POSIX IPC](https://www.systutorials.com/docs/linux/man/7-shm_overview/) and now it is possible to connect multiple ues (tried 2) to a enb, while each application is running in its own Docker container and all ues connect to the enbs shared memory.

@jgiovatto I authored a pull request to add these changes to your code

**Comment by GinesGarcia** [comment]
Hi,
@FabianEckermann Which steps should I follow to run each application in a docker using the same shared memory?

Thanks in advance!

**Comment by pgorczak** [comment]
We probably want to be able to build eNB and UE even if no RF drivers are found. Currently CMake [checks](https://github.com/jgiovatto/srsLTE/blob/b75506ac1687b571cf86e58d65a41e58fbc927fb/CMakeLists.txt#L177) for Blade, UHD or Soapy and [disables](https://github.com/jgiovatto/srsLTE/blob/b75506ac1687b571cf86e58d65a41e58fbc927fb/CMakeLists.txt#L437) eNB and UE if none of them were found.

**Comment by pgorczak** [comment]
@GinesGarcia @FabianEckermann I made a minimal example in [srslte-docker-emulated](https://github.com/pgorczak/srslte-docker-emulated).

**Comment by ravens** [comment]
Is there any plan to further integrate this ? having the fauxRF could really helps to build elements for testing elements in the cellular ecosystem - we can embed a srsUE+srsLTE inside a CI/CD chain for example. Thanks !

**Comment by andrepuschmann** [comment]
Hey guys, all of Joe's work on this fake RF driver has been great and is highly appreciated. However, there are some limitations to using shmem in terms of scalability, for example. This will be important for large scale CI/CD testing, which is exactly what we are after. We've therefore decided to design an alternative fake RF driver based on ZMQ. A first version of that driver will be released in srsLTE 19.03. It would be great to see your opinions and contributions to that.

**Pull request closed without merging**
