### PR TITLE
Clarify LimeSDR support status.

### LINKED ISSUE #84: core dump issue with the srsue binary
I tried to setup an LTE test environment with both: 
- the srsUE program using a **limeSDR** for the UE part
- the Amarisoft LTE 100EPC for the EPC part

I installed all the dependencies and everything compiled successfully, but during the cell attachment, just after the SIB2 has been received, I got a core dump error from the srsue binary...

I tried with both  VM (Ubuntu 17.04 kernel classic & lowlatency) and a bare computer (Ubuntu 16.04 kernel lowlatency).

Here is the log from the srsue binary : https://pastebin.com/jrMjinWU
And here is the end of the log file provided in debug mode : https://pastebin.com/d5uAwUgX
I can provide you the full file if you want to, but it's pretty huge...

So I don't have a clue about where does the issue can come from... Maybe you'll be able to help me with that ?

### PR DESCRIPTION
**Pull request by Manouchehri**
Fixes #84.

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Hey, we are working on fixing the Tx support for the Lime and will have full compatibility in the next release. Skipping this PR therefore.
Thanks

**Comment by Manouchehri** [comment]
Awesome, great to hear! 🙂

**Comment by Manouchehri** [comment]
@andrepuschmann Still hoping for LimeSDR compatibility in the next release? =)

**Comment by cloudguru-bb** [comment]
Hi,

I second that. Lime SDR support is very much needed.

Brian

**Comment by SigPloiter** [comment]
Hello 

Has there been any updates for Limesdr support, specially limeSDR mini ?

**Comment by andrepuschmann** [comment]
LimeSDR, including the mino, is supported through SoapySDR.

**Comment by Manouchehri** [comment]
I can confirm that the LimeSDR does indeed work with srsLTE. =) 

Thanks for the great project!

**Pull request closed without merging**
