### PR TITLE
Hex log format check

### PR DESCRIPTION
**Pull request by jgiovatto**
Added printf format check for hex_log methods. Changed signature to use const char * vs string object to save on object creation. Attempted to correct 1 hex log that threw a warning.

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Cherry-picked. Thanks.

**Comment by jgiovatto** [comment]
Hi, Looks like I missed the "const uint8_t*" signature of the virtual function.
Fix applied below, looks like using pure virtual may be a better way to go.

diff --git a/lib/include/srslte/common/log.h b/lib/include/srslte/common/log.h
index 7d8f0a8c..d1ca14cf 100644
--- a/lib/include/srslte/common/log.h
+++ b/lib/include/srslte/common/log.h
@@ -129,14 +129,10 @@ public:
   virtual void debug(const char * message, ...)   __attribute__ ((format (printf, 2, 3))) = 0;
 
   // Same with hex dump
-  virtual void error_hex(uint8_t *hex, int size, const char *, ...)   __attribute__((format (printf, 4, 5)))
-    {error("error_hex not implemented.\n");}
-  virtual void warning_hex(uint8_t *hex, int size, const char *, ...) __attribute__((format (printf, 4, 5)))
-    {error("warning_hex not implemented.\n");}
-  virtual void info_hex(uint8_t *hex, int size, const char *, ...)    __attribute__((format (printf, 4, 5)))
-    {error("info_hex not implemented.\n");}
-  virtual void debug_hex(uint8_t *hex, int size, const char *, ...)   __attribute__((format (printf, 4, 5)))
-    {error("debug_hex not implemented.\n");}
+  virtual void error_hex(const uint8_t *hex, int size, const char *, ...)   __attribute__((format (printf, 4, 5))) = 0;
+  virtual void warning_hex(const uint8_t *hex, int size, const char *, ...) __attribute__((format (printf, 4, 5))) = 0;
+  virtual void info_hex(const uint8_t *hex, int size, const char *, ...)    __attribute__((format (printf, 4, 5))) = 0;
+  virtual void debug_hex(const uint8_t *hex, int size, const char *, ...)   __attribute__((format (printf, 4, 5))) = 0;
 
 protected:
   std::string get_service_name() { return service_name; }

**Comment by FFY00** [comment]
@jgiovatto you should paste the patch inside a code block :blush:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by andrepuschmann** [comment]
Hey, we've fixed that already and pushed to master. Thanks for reporting anyways.

**Pull request closed without merging**
