### PR TITLE
enb: add bind address for s1ap connection

### PR DESCRIPTION
**Pull request by bjoern-r**
add s1c_bind_addr config option to specify the local bind address used for S1AP connections instead of using the GTP address.
This allows operation on setups with split S1U and S1C networks.

I've testded this sucessfully with Open5Gcore CN, USRP B210 and Pixel UE.

### CODE REVIEW

**Comment by bjoern-r** [comment]
this would fix #127

**Comment by andrepuschmann** [comment]
Is this still relevant for release 18.03?

**Comment by dongxusb** [comment]
hi,have you tested in srsLTE to split S1U and S1C networks.? i want to know that you changed the srsenb code and add a interface, whether the srsepc code needs to be changed to match the srsenb code.Recently i want to  split the srsepc into spgw and mme/hss that run in two computer separately,if you can give any help,i  will be very grateful.my email is 596842764@qq.com

**Comment by bjoern-r** [comment]
I did not use the srsepc i use our own EPC that aleady uses split s1u and s1c. 
The changes i did to the srsenb are in the patch above.

**Comment by dongxusb** [comment]
your own EPC? May i know whether it is open-sourced?where i can get access to it ?

**Comment by andrepuschmann** [comment]
Hey @bjoern-r , are you willing to sign the CLA in order for us to merge that in?

**Comment by bjoern-r** [comment]
@dongxusb We are using the Open5Gcore EPC, which is available by license. You may contact me for further details.

**Comment by bjoern-r** [comment]
@andrepuschmann I have to check this because my day-job is in the EPC business and i may not allowed to do so.

**Comment by dongxusb** [comment]
hi，bjoern-r ，whether the Open5Gcore EPC is open-sourced？Can i find it in the GitHub？ or where can i get more information about the Open5Gcore EPC ？

**Comment by bjoern-r** [comment]
@dongxusb please check: https://www.open5gcore.org/

**Comment by andrepuschmann** [comment]
Thanks again for that.

**Pull request merged**
